plugins {
    id 'java'
}

group = 'com.tvzs'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.9'
    implementation("com.google.guava:guava:28.2-jre")
}

compileJava {
    options.encoding = 'UTF-8'
}